require("dotenv").config();
const { Pool } = require("pg");

const dbClient = new Pool({
  user: process.env.DB_USER,
  host: process.env.DB_HOST,
  database: process.env.DB_DATABASE,
  password: process.env.DB_PASSWORD,
  port: process.env.DB_PORT,
  max: 10,
  idleTimeoutMillis: 30000,
});

const slugs = [
  //   "starseeker-astroneer-expeditions",
  //   "lords-of-the-fallen-2",
  //   "noir-total-deadly-party",
  //   "mortal-quest",
  //   "exovia",
  //   "grand-theft-auto-vi",
  //   "ghost-sector",
  //   "hallow-maze",
  //   "my-heavens-dale",
  //   "fiefdom--1",
  //   "omnn",
  //   "duskfade--1",
  //   "heros-hand",
  //   "project-shinigami-hime",
  //   "project-kyouran",
  //   "cthulhu-the-cosmic-abyss",
  //   "cozy-beach",
  //   "recital-of-the-heart",
  //   "tom-the-postgirl",
  //   "port-valley",
  //   "beautiful-light",
  //   "frond-online",
  //   "outbound",
  //   "puzkin-magnetic-odyssey",
  //   "bloodletter--1",
  //   "skyclimbers",
  //   "world-of-dogs",
  //   "a-wake-inn-rebooked",
  //   "do-not-play",
  //   "groda",
  //   "replaced",
  //   "polda-8",
  //   "the-duskbloods",
  //   "super-adventure--1",
  //   "bless-you-again",
  //   "100-caliber-dash",
  //   "fable--1",
  //   "the-pet-squad",
  //   "wind-runners",
  //   "melted-time",
  //   "paws-and-leaves-a-last-tale",
  //   "bad-girl",
  //   "hexlands",
  //   "galago",
  //   "nightborn",
  //   "into-the-void--4",
  //   "screamer--1",
  //   "potion-in-motion",
  //   "danchi-days",
  //   "redemption-of-the-damned",
  //   "problem-solver-club",
  //   "exodus--5",
  //   "lootbound",
  //   "enginefall",
  //   "crimson-frontier",
  //   "marvel-1943-rise-of-hydra--1",
  //   "fruit-of-choice",
  //   "neptunegl",
  //   "wax-heads",
  //   "blood-peace",
  //   "theres-always-a-madman-the-macguffin",
  //   "sugar-sling-showdown",
  //   "the-dark-rites-of-arkham",
  //   "silent-planet",
  //   "psycasso--1",
  //   "cereal-reaper",
  //   "sacrifire",
  //   "insectile",
  //   "dread-pilots",
  //   "moonbrella",
  //   "shell-bless-the-faithless",
  //   "terror-type-alchemy",
  //   "love-in-space--1",
  //   "witches-tavern",
  //   "dr-dot-mememe-want-to-sleep",
  //   "loop-new-reality",
  //   "breathedge-2",
  //   "nine-rounds-rapid",
  //   "ice-on-the-edge",
  //   "aurora-polaris",
  //   "questing",
  //   "unravel-trigger-cold-war",
  //   "dragon-ball-z-kakarot-daima-adventure-through-the-demon-realm-part-2",
  //   "hand-of-hexes",
  //   "nonuple-nine-asymptote",
  //   "aokaki",
  //   "summer-lesson-allison-snow-nanokakan-no-niwa",
  //   "in-a-world-after-people",
  //   "kickboxer",
  //   "catena",
  //   "abyss-x-zero",
  //   "bleakwood",
  //   "brave-new-wonders",
  //   "the-shadow-syndicate",
  //   "advaria-chronicles-of-immortality",
  //   "archeage-chronicles",
  //   "undefeated-genesis",
  //   "ikuma-the-frozen-compass",
  //   "star-wars-zero-company",
  //   "rhythm-heaven-groove",
  //   "tomodachi-life-living-the-dream",
  //   "thick-as-thieves",
  //   "cappy-and-tappy-temples-of-peril",
  //   "animal-use-protocol",
  //   "dicewood",
  //   "prince-of-persia-the-sands-of-time--3",
  //   "pinata-puppy-world",
  //   "a-forest-tale-porasy",
  //   "dragons-brew",
  //   "onimusha-way-of-the-sword",
  //   "toem-2",
  //   "the-occultist",
  //   "immortal-boy",
  //   "liminal-point",
  //   "dark-mass",
  //   "slain-2-the-beast-within",
  //   "axyn-adventure",
  //   "frostpunk-1886",
  //   "tales-of-tuscany",
  //   "your-crown-is-mine",
  //   "missi",
  //   "hexceed-violaceum",
  //   "forge-of-the-fae",
  //   "raev-kingdom-on-the-distant-shores",
  //   "the-backworld",
  //   "rootbound--1",
  //   "skateboard-knight",
  //   "absym",
  //   "the-house-in-the-hollow",
  //   "curilemu",
  //   "5-star-fishy",
  //   "knights-province",
  //   "hanoi-puzzles-spin-match",
  //   "lapso--1",
  //   "super-mario-bros-extreme-adventure",
  //   "coring",
  //   "lunar-new-year",
  //   "shotfightdisaster",
  //   "changer-seven",
  //   "arma-4",
  //   "take-us-north",
  //   "decapolice",
  //   "pilotxross",
  //   "nerd-tracing-dayline",
  //   "nak",
  //   "untrusted-hackers-at-large",
  //   "mearcair-slash-system-pulse",
  //   "margaritari",
  //   "waifu-wars-online",
  //   "neo-ha-bits",
  //   "former-dawn--1",
  //   "former-dawn",
  //   "codex-eternal-eclipse",
  //   "the-god-slayer",
  //   "cocoro",
  //   "kijutsu-rider",
  //   "heart-dungeon",
  //   "saros",
  //   "steampunk-shinobi",
  //   "sligga-trigger",
  //   "constellations-beyond-the-edges",
  //   "afterthedawn",
  //   "grimmlins-tale",
  //   "project-faith",
  //   "threat-vector",
  //   "kings-and-savages",
  //   "rise-of-the-robots-x",
  //   "open-air",
  "chi-project",
  "ominous-recall",
  "scramble-heart-city",
  "elementalist",
  "solar-voltage",
  "theres-always-a-madman-victor",
  "possible-one-lunar-industries",
  "loop-craft",
  "escape-of-the-hammer-princess",
  "smipat-and-the-lost-bones",
  "moonlight-peaks",
  "project-dosa",
  "hero-chest",
  "hanoi-puzzles-magnetrix",
  "ink-shapes-book-one",
  "pocket-wheels",
  "iridescent--1",
  "prisma",
  "feltopia",
  "exil",
  "telluria-forebodings",
  "the-last-grape",
  "the-alchemist",
  "squadron-42",
  "clock-overwhelmed",
  "project-mix",
  "no-vacation-for-an-executioner",
  "plague-hunter",
  "inazuma-eleven-re",
  "in-the-valley-of-gods",
  "peacemaker-bloody-emperor",
  "playable-alpha",
  "nekopara-sekai-connect",
];

const checkGameSlugsInDb = async (slugs) => {
  console.log(slugs.length);
  const existingGames = [];
  const missingSlugs = [];

  for (const slug of slugs) {
    const result = await dbClient.query(
      "SELECT id, slug FROM games WHERE slug = $1 LIMIT 1",
      [slug]
    );

    if (result.rows.length > 0) {
      //   existingGames.push({
      //     slug: result.rows[0].slug,
      //     strapiGameId: result.rows[0].id,
      //   });
      existingGames.push(result.rows[0].id);
    } else {
      missingSlugs.push(slug);
    }
  }
  console.log({
    total: slugs.length,
    existing: existingGames.length,
    missing: missingSlugs.length,
    existingGames,
    missingSlugs,
  });
  return {
    total: slugs.length,
    existing: existingGames.length,
    missing: missingSlugs.length,
    existingGames,
    missingSlugs,
  };
};
checkGameSlugsInDb(slugs);
